// Frontend/React/hudir/src/components/Image.js
import axios from "axios";
import { useEffect, useState } from "react";
import { BACKEND_URL } from "../constants";

function Image(props) {

    const [source, setSource] = useState(null);

    useEffect(() => {
        if(props.endpoint !== undefined){
            axios
            .get(
                BACKEND_URL.concat(props.endpoint),
                { responseType: 'arraybuffer'},
            )
            .then(response => {
                const base64 = btoa(
                    new Uint8Array(response.data).reduce(
                        (data, byte) => data + String.fromCharCode(byte),
                        '',
                    ),
                );
                setSource("data:;base64," + base64);
            });
        }
        if(props.image !== undefined){
            const base64 = btoa(
                new Uint8Array(props.image).reduce(
                    (data, byte) => data + String.fromCharCode(byte),
                    '',
                ),
            );
            setSource("data:;base64," + base64);
        }
    }, []);

    return(
        <img src={source} className={props.className} />
    );

}

export default Image;

// Frontend/Vue/hudir/src/components/Image.vue
<template>
    <img :src="source" :className="className" />
</template>

<script>
    import axios from "axios";
    import { BACKEND_URL } from "../constants";

    export default {
        name: "Image",
        props: [
            'endpoint',
            'image', 
            'className'
        ],
        data() {
            return {
                'source': null
            }
        },
        mounted() {
            if(this.endpoint !== undefined){
                axios
                .get(
                    BACKEND_URL.concat(this.endpoint),
                    { responseType: 'arraybuffer'},
                )
                .then(response => {
                    const base64 = btoa(
                        new Uint8Array(response.data).reduce(
                            (data, byte) => data + String.fromCharCode(byte),
                            '',
                        ),
                    );
                    this.source = "data:;base64," + base64;
                });
            }
            if(this.image !== undefined){
                const base64 = btoa(
                    new Uint8Array(this.image).reduce(
                        (data, byte) => data + String.fromCharCode(byte),
                        '',
                    ),
                );
                this.source = "data:;base64," + base64;
            }
        }
    }
</script>

<style>
    
</style>
