// Frontend/Angular/hudir/src/app/posts/posts.component.ts
import { HttpClient } from '@angular/common/http';
import { Component, Input, OnInit, ViewEncapsulation } from '@angular/core';
import { forkJoin } from 'rxjs';
import { BACKEND_URL } from '../constants';

type Posts = {
  posts: Post[];
};

type Post = {
  id: string;
  name: string;
  description: string;
  path: string;
  likes: number;
  userId: number;
  createdAt: Date;
  updatedAt: Date;
};

@Component({
  selector: 'app-posts',
  templateUrl: './posts.component.html',
  styleUrls: ['./posts.component.css'],
  encapsulation: ViewEncapsulation.None
})
export class PostsComponent implements OnInit {

  @Input() from = '';
  @Input() currentPost = '';
  @Input() username = '';
  @Input() number = -1;

  posts: Post[] = [];
  images: ArrayBuffer[] = [];
  loading =  true;
  userPostSquare = 'user-post-square';

  constructor(private http: HttpClient) { }

  ngOnInit(): void {
    var endpoint = BACKEND_URL.concat("/post/");
    if(this.from === "user"){
      endpoint = endpoint.concat("getPostsFromUser/").concat(this.username);
    }
    if(this.from === "all"){
      endpoint = endpoint.concat("allPosts/");
    }
    this.http.get<Posts>(endpoint)
      .subscribe(res => {
        console.log(res.posts);
        let filterPosts: Post[] = [];
        let requests = [];
        for(var i = 0; i < res.posts.length; i++){
          if(res.posts[i].id === this.currentPost) continue;
          if(i === this.number) break;
          filterPosts.push(res.posts[i]);
          requests.push(
            this.http.get(
                BACKEND_URL.concat("/post/getPostPicture/").concat(res.posts[i].id),
                { responseType: 'arraybuffer'},
            ) 
          );
        }
        this.posts = filterPosts;
        forkJoin(requests).subscribe({
          next: (responses) =>{
            for(var i = 0; i < responses.length; i++){
              this.images.push(responses[i]);
            }
          }, 
          error: (err) => {
            console.log(err);
          }, 
          complete: () => {
            this.loading = false;
          }});
      })
  }

}

<div class="flex flex-wrap mx-0">
    <div *ngIf="loading">LOADING</div>
    <ng-container *ngIf="!loading">
        <div  *ngFor="let post of posts; index as i" [class]="number === -1 ? 'user-post-square' : 'more user-post-square'">
            <div class="user-post">
                <a [href]="'/post/'.concat(post.id)" class="w-full h-full"> 
                    <app-image [image]="images[i]" className="min-w-full min-h-full object-cover"></app-image> 
                </a>
            </div>
        </div>  
    </ng-container>  
</div>

// Frontend/React/hudir/src/components/Posts.js
import { useEffect, useState } from "react";
import axios from "axios";
import { BACKEND_URL } from "../constants";
import Image from "./Image";
import "./Posts.css";

function Posts(props){
    	
    const [posts, setPosts] = useState(null);
    const [postImages, setPostImages] = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        var endpoint = BACKEND_URL.concat("/post/");
        if(props.from === "user"){
            endpoint = endpoint.concat("getPostsFromUser/").concat(props.username);
        }
        if(props.from === "all"){
            endpoint = endpoint.concat("allPosts/");
        }
        axios
            .get(
                endpoint,
            )
            .then(response => {
                console.log(response.data.posts);
                let filterPosts = [];
                let requests = [];
                for(var i = 0; i < response.data.posts.length; i++){
                    console.log(props.currentPost);
                    if(response.data.posts[i].id == props.currentPost) continue;
                    if(i == props.number) break;
                    filterPosts.push(response.data.posts[i]);
                    requests.push(
                        axios.get(
                            BACKEND_URL.concat("/post/getPostPicture/").concat(response.data.posts[i].id),
                            { responseType: 'arraybuffer'},
                        ) 
                    );
                }
                console.log(requests);
                axios.all(requests)
                    .then(axios.spread((...responses) => {
                        setPostImages(responses);
                        setLoading(false);
                    }))
                    .catch(errors => {
                        console.log(errors);
                    })
                setPosts(filterPosts);
            });
        
    }, []);

    return(
        <div className="flex flex-wrap mx-0">
            {
                loading ? (
                    <></>
                ) : (
                    <>
                       {
                           posts.map((post, index) => {
                                return (
                                    <div className={(props.number !== undefined) ? ("user-post-square more") : ("user-post-square")} key={index}>
                                        <div className="user-post">
                                            <a href={"/post/".concat(post.id)} key={post.id} className="w-full h-full"> 
                                                <Image image={postImages[index].data} className="min-w-full min-h-full object-cover" /> 
                                            </a>
                                        </div>
                                    </div>  
                                );
                           })
                       }
                    </>
                )
            }
        </div>
    );

}

export default Posts;
