// Frontend/React/hudir/src/components/Signup.js
import { useState } from "react";
import AuthService from "../services/auth.service";

function Signup(props){

    const [singUpForm, setSignUpForm] = useState({username: '', email: '', password:''});
    const [repeatedPassword, setRepeatedPassword] = useState('');
    const [error, setError] = useState('');

    async function onSubmit(e){
        e.preventDefault();
        setError("");
        if(!validatePassword()){
            e.stopPropagation();
        } else {
            AuthService.register(singUpForm.username, singUpForm.email, singUpForm.password).then(
                (response) => {
                    setError(response.data.message);
                },
                (error) => {
                    const resMsg = 
                        (error.response &&
                            error.response.data &&
                            error.response.data.message) ||
                        error.message ||
                        error.toString();
                    setError(resMsg);
                }
            );
        }
    }

    function onChange(event) {
        validatePassword();
        const {name, value} = event.target;
        let newForm = {username: singUpForm.username, email: singUpForm.email, password: singUpForm.password};
        newForm[name] = value;
        setSignUpForm(newForm);
    }

    const onChangeRepeatedPassword = (e) => {
        const password = e.target.value;
        setRepeatedPassword(password);
    }

    function validatePassword(){
        var password1 = document.getElementById("password"), password2 = document.getElementById("confirm_password");
        if(password1.value !== password2.value) {
            password2.setCustomValidity("Passwords Don't Match");
            return false;
        } else {
            password2.setCustomValidity('');
            return true;
        }
    }

    return(
        <div className='flex justify-center mt-32'>
            <form className='bg-gray-500 shadow-md rounded px-8 pt-6 pb-8 mb-4' onSubmit={onSubmit}>
                <div>
                    <label className='block text-gray-700 text-sm font-bold mb-2' htmlFor="email">Email</label>
                    <input 
                        required 
                        type="email"
                        name="email"
                        value={singUpForm.email}
                        onChange={onChange}
                        placeholder="email"
                        className='rounded w-full py-2 px-3 text-gray-700 focus:outline-none focus:shadow-outline'
                    />
                </div>
                <div>
                    <label className='block text-gray-700 text-sm font-bold mb-2' htmlFor="username">Username</label>
                    <input 
                        required
                        type="text"
                        name="username"
                        value={singUpForm.username}
                        onChange={onChange}
                        placeholder="username"
                        className='rounded w-full py-2 px-3 text-gray-700 focus:outline-none focus:shadow-outline'
                    />
                </div>
                <div>
                    <label className='block text-gray-700 text-sm font-bold mb-2' htmlFor="password">Password</label>
                    <input 
                        required
                        type="password"
                        name="password"
                        value={singUpForm.password}
                        onChange={onChange}
                        id="password"
                        placeholder="password"
                        className='rounded w-full py-2 px-3 text-gray-700 focus:outline-none focus:shadow-outline'
                    />
                </div>
                <div>
                    <label className='block text-gray-700 text-sm font-bold mb-2' htmlFor="confirm_password">Repeat password</label>
                    <input 
                        required
                        type="password"
                        name="confirm_password"
                        value={repeatedPassword}
                        onChange={onChangeRepeatedPassword}
                        placeholder="password"
                        id="confirm_password"
                        onKeyUp={validatePassword}
                        className='rounded w-full py-2 px-3 text-gray-700 focus:outline-none focus:shadow-outline'
                    />
                </div>     
                <button className="bg-[#2a9fd6] hover:bg-[#0b73a0] text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline mt-2" type="submit">Signup</button>
                <div>
                    <span>{error}</span>
                </div>
            </form>
        </div>
    );
}

export default Signup;

// Frontend/Angular/hudir/src/app/signup/signup.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthService } from '../_services/auth.service';
@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.css']
})
export class SignupComponent implements OnInit {
  form: any = {
    username: null,
    email: null,
    password: null
  };
  isSuccessful = false;
  isSignUpFailed = false;
  errorMessage = '';
  constructor(private authService: AuthService) { }
  ngOnInit(): void {
  }
  onSubmit(): void {
    const { username, email, password } = this.form;
    this.isSuccessful = false;
    this.authService.register(username, email, password).subscribe({
      next: data => {
          this.isSuccessful = true;
          this.isSignUpFailed = false;
          this.errorMessage = data.message;
        },
      error: err => {
          this.errorMessage = err.error.message;
          this.isSignUpFailed = true;
        }
    });
  }
}
<div class='flex justify-center mt-32'>
    <form 
        class='bg-gray-500 shadow-md rounded px-8 pt-6 pb-8 mb-4' 
        name="form"
        (ngSubmit)="onSubmit()"
        #f="ngForm"
        novalidate
    >
        <div>
            <label class='block text-gray-700 text-sm font-bold mb-2' htmlFor="email">Email</label>
            <input 
                [(ngModel)]="form.email"
                #email="ngModel"
                required 
                type="email"
                name="email"
                placeholder="email"
                class='rounded w-full py-2 px-3 text-gray-700 focus:outline-none focus:shadow-outline'
            />
        </div>
        <div>
            <label class='block text-gray-700 text-sm font-bold mb-2' htmlFor="username">Username</label>
            <input 
                [(ngModel)]="form.username"
                #username="ngModel"
                required
                type="text"
                name="username"
                placeholder="username"
                class='rounded w-full py-2 px-3 text-gray-700 focus:outline-none focus:shadow-outline'
            />
        </div>
        <div>
            <label class='block text-gray-700 text-sm font-bold mb-2' htmlFor="password">Password</label>
            <input 
                [(ngModel)]="form.password"
                #password="ngModel"
                required
                type="password"
                name="password"
                id="password"
                placeholder="password"
                class='rounded w-full py-2 px-3 text-gray-700 focus:outline-none focus:shadow-outline'
            />
        </div>
        <div>
            <label class='block text-gray-700 text-sm font-bold mb-2' htmlFor="confirm_password">Repeat password</label>
            <input 
                [(ngModel)]="form.confirm_password"
                #confirm_password="ngModel"
                required
                type="password"
                name="confirm_password"
                placeholder="password"
                id="confirm_password"
                class='rounded w-full py-2 px-3 text-gray-700 focus:outline-none focus:shadow-outline'
            />
        </div>     
        <button class="bg-[#2a9fd6] hover:bg-[#0b73a0] text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline mt-2" type="submit">Signup</button>
        <div *ngIf="isSuccessful">
            <span >User registered successfully!</span>
        </div>
    </form>
</div>
