// Frontend/React/hudir/src/components/Comment.js
import Image from "./Image";
import "./Comment.css";

function Comment(props){

    return(
        <div className="flex comment">
            <Image endpoint={"/user/pfp/".concat(props.username)} className="profile_picture comment-picture" />&nbsp;
            <div>
                <a href={"/user/".concat(props.username)}>{props.username}</a>
                <p className="comment-content" >{props.content}</p>
            </div>
        </div>
    );

}

export default Comment;

// Frontend/Angular/hudir/src/app/comment/comment.component.ts
import { Component, Input, OnInit, ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'app-comment',
  templateUrl: './comment.component.html',
  styleUrls: ['./comment.component.css'],
  encapsulation: ViewEncapsulation.None
})
export class CommentComponent implements OnInit {

  @Input() username: string = "";
  @Input() content: string = "";

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="flex comment">
    <app-image [endpoint]="'/user/pfp/'.concat(this.username)" className="comment-picture"></app-image>&nbsp;
    <div>
        <a [href]="'/user/'.concat(this.username)">{{username}}</a>
        <p class="comment-content" >{{content}}</p>
    </div>
</div>
