// Frontend/Vue/hudir/src/components/Upload.vue
<template>
    <div className='flex justify-center mt-32'>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossOrigin="anonymous"/>
        <form className='bg-gray-500 shadow-md rounded px-8 pt-6 pb-8 mb-4 basis-96' @submit.prevent="onSubmit">
            <div className="flex flex-col">
                <label htmlFor="fileToUpload" className="hover:cursor-pointer link"><i className="fas fa-upload">
                    </i>&nbsp;Add&nbsp;image&nbsp;
                </label>
                <input 
                    required
                    type="file"
                    name="fileToUpload"
                    accept="image/*"
                    @input="newImage"
                    className='custom-file-input'
                    id='fileToUpload'
                />
                <img v-if="showPreview" className="object-contain" :src="preview" />
            </div>
            <div>
                <label htmlFor="name">Name</label>
                <input 
                    v-model="postForm.name"
                    required
                    type="text"
                    name="name"
                    placeholder="Name"
                    className='rounded w-full py-2 px-3 text-gray-700 focus:outline-none focus:shadow-outline'
                />
            </div>
            <div>
                <label htmlFor="description">Description</label>
                <textarea 
                    v-model="postForm.description"
                    required
                    name="description"
                    placeholder="Description"
                    className='class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"'
                />
            </div>
            <button className="bg-[#2a9fd6] hover:bg-[#0b73a0] text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                Post
            </button>
                {{message}}
        </form>
    </div>
</template>

<script>
    import axios from 'axios';
    import { BACKEND_URL } from '../constants';

    export default {
        name: "Upload",
        data() {
            return {
                'postForm': {
                    name: '',
                    description: ''
                },
                'image': null,
                'preview': null,
                'message': '',
                'objectUrl': null
            }
        },
        computed: {
            currentUser() {
                return this.$store.state.auth.user;
            },
            showPreview() {
                return this.preview !== null;
            }
        },
        unmounted() {
            URL.revokeObjectURL(this.objectUrl);
        },  
        methods: {
            newImage(e){
                this.image = e.target.files[0];
                this.objectUrl = URL.createObjectURL(this.image);
                this.preview = this.objectUrl;
            },
            onSubmit(e){
                this.message = "";
                const formData = new FormData();
                formData.append('name', this.postForm.name);
                formData.append('description', this.postForm.description);
                formData.append('userId', this.currentUser.id);
                formData.append('image', this.image);

                axios
                    .post(BACKEND_URL.concat('/post/upload'), formData)
                    .then(response => {
                        console.log(response);
                        this.$router.push("/post/".concat(response.data.id));
                    })
                    .catch(err => {
                        console.log(err);
                    })
                    }
            }
        }
</script>

<style>

</style>

// Frontend/Angular/hudir/src/app/upload/upload.component.ts
import { HttpClient } from '@angular/common/http';
import { Component, OnInit, ViewEncapsulation } from '@angular/core';
import { TokenStorageService } from '../_services/token-storage.service';
import { BACKEND_URL } from '../constants';
import { Router } from '@angular/router';
import { DomSanitizer } from '@angular/platform-browser';

class User {
  username: string = "";
  id: number = 0;
}

type Post = {
  id: string;
}

@Component({
  selector: 'app-upload',
  templateUrl: './upload.component.html',
  styleUrls: ['./upload.component.css'],
  encapsulation: ViewEncapsulation.None
})
export class UploadComponent implements OnInit {

  postForm: any = {
    postName: "",
    descirption: ""
  };
  image!: File;
  preview: string = "";
  message: string = "";
  objectUrl: string = "";
  currentUser: User = new User();
  isLoggedIn = false;

  constructor(
    private http: HttpClient, 
    private tokenStorage: TokenStorageService, 
    private _router: Router, 
    private sanitizer: DomSanitizer
  ) { }

  ngOnInit(): void {
    this.isLoggedIn = !!this.tokenStorage.getToken();
    if (this.isLoggedIn) {
      this.currentUser = this.tokenStorage.getUser();
      console.log(this.tokenStorage.getUser());
    }
  }

  ngOnDestroy(): void {
    URL.revokeObjectURL(this.objectUrl);
  }

  onSubmit(): void{
    this.message = "";
    const formData = new FormData();
    formData.append('name', this.postForm.postName);
    formData.append('description', this.postForm.description);
    formData.append('userId', this.currentUser.id.toString());
    formData.append('image', this.image);

    this.http
        .post<Post>(BACKEND_URL.concat('/post/upload'), formData)
        .subscribe({
          next: response => {
            console.log(response);
            this._router.navigateByUrl('/post/'.concat(response.id))
              .then(() => {
                window.location.reload();
              });
        },
        error: err => {
            console.log(err);
        }});
  };

  newImage(e: Event): void{
    const target = e.target as HTMLInputElement;
    if(target.files !== null){
      this.image = target.files[0];
      this.objectUrl = this.sanitizer.bypassSecurityTrustUrl(URL.createObjectURL(this.image)) as string;
      console.log(this.objectUrl);
      this.preview = this.objectUrl;
    }
  }

  showPreview() {
    return this.preview !== "";
  }
}

<div class='flex justify-center mt-32'>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossOrigin="anonymous"/>
    <form class='bg-gray-500 shadow-md rounded px-8 pt-6 pb-8 mb-4 basis-96' (ngSubmit)="onSubmit()" #f="ngForm">
        <div class="flex flex-col">
            <label class="hover:cursor-pointer link"><i class="fas fa-upload">
                </i>&nbsp;Add&nbsp;image&nbsp;
                <input 
                required
                type="file"
                name="fileToUpload"
                accept="image/*"
                (input)="newImage($event)"
                class='custom-file-input'
                id='fileToUpload'
                />
            </label>
            
            <img *ngIf="showPreview()" className="object-contain" [src]="preview" />
        </div>
        <div>
            <label htmlFor="name">Name</label>
            <input 
                [(ngModel)]="postForm.postName"
                #postName="ngModel"
                required
                type="text"
                name="name"
                placeholder="Name"
                class='rounded w-full py-2 px-3 text-gray-700 focus:outline-none focus:shadow-outline'
            />
        </div>
        <div>
            <label htmlFor="description">Description</label>
            <textarea 
                [(ngModel)]="postForm.description"
                #description="ngModel"
                required
                name="description"
                placeholder="Description"
                class='class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"'
            ></textarea>
        </div>
        <button class="bg-[#2a9fd6] hover:bg-[#0b73a0] text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
            Post
        </button>
            {{message}}
    </form>
</div>
