// Frontend/React/hudir/src/components/Login.js
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import AuthService from '../services/auth.service';

function Login(props){

    const [username, setUsername] = useState('');
    const [password, setPassword] = useState('');
    const [error, setError] = useState("");
    let navigate = useNavigate();

    async function onSubmit(e) {
        e.preventDefault();
        setError("");
        AuthService.login(username, password).then(
            () => {
                navigate("/");
                window.location.reload();
            },
            (error) => {
                const resMsg = 
                    (error.response &&
                        error.response.data &&
                        error.response.data.message) ||
                    error.message ||
                    error.toString();
                setError(resMsg);
            }
        );
    }

    const onChangeUsername = (e) => {
        const username = e.target.value;
        setUsername(username);
    };

    const onChangePassword = (e) => {
        const password = e.target.value;
        setPassword(password);
    };

    return(
        <div className='flex justify-center mt-32'>
            <form className='bg-gray-500 shadow-md rounded px-8 pt-6 pb-8 mb-4' onSubmit={onSubmit}>
                <div className='mb-4'>
                    <label className='block text-gray-700 text-sm font-bold mb-2' htmlFor="username">Username</label>
                    <input 
                        required
                        type="text"
                        name="username"
                        value={username}
                        onChange={onChangeUsername}
                        placeholder="username"
                        className='rounded w-full py-2 px-3 text-gray-700 focus:outline-none focus:shadow-outline'
                    />
                </div>
                <div>
                    <label className="block text-gray-700 text-sm font-bold mb-2" htmlFor="password" >Password</label>
                    <input 
                        required
                        type="password"
                        name="password"
                        value={password}
                        onChange={onChangePassword}
                        placeholder="password"
                        className='class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"'
                    />
                </div>
                <button className="bg-[#2a9fd6] hover:bg-[#0b73a0] text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                Login
                </button>
                {error}
            </form>
        </div>   
    );
}

export default Login;

// Frontend/Angular/hudir/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthService } from '../_services/auth.service';
import { TokenStorageService } from '../_services/token-storage.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  form: any = {
    username: null,
    password: null
  };
  isLoggedIn = false;
  isLoginFailed = false;
  errorMessage = '';
  roles: string[] = [];
  constructor(private authService: AuthService, private tokenStorage: TokenStorageService, private _router: Router) { }
  ngOnInit(): void {
    if (this.tokenStorage.getToken()) {
      this.isLoggedIn = true;
      this.roles = this.tokenStorage.getUser().roles;
    }
  }
  onSubmit(): void {
    const { username, password } = this.form;
    this.authService.login(username, password).subscribe({
      next: data => {
        this.tokenStorage.saveToken(data.accessToken);
        this.tokenStorage.saveUser(data);
        this.isLoginFailed = false;
        this.isLoggedIn = true;
        this.roles = this.tokenStorage.getUser().roles;
        this._router.navigateByUrl('/user/'.concat(this.tokenStorage.getUser().username))
          .then(() => {
            window.location.reload();
          });
      },
      error: err => {
        this.errorMessage = err.error.message;
        this.isLoginFailed = true;
      }
    }
    );
  }
  reloadPage(): void {
    window.location.reload();
  }
}
<div class='flex justify-center mt-32'>
    <form 
        *ngIf="!isLoggedIn"
        name="form"
        (ngSubmit)="onSubmit()"
        #f="ngForm"
        novalidate
        class='bg-gray-500 shadow-md rounded px-8 pt-6 pb-8 mb-4' 
    >
        <div class='mb-4'>
            <label class='block text-gray-700 text-sm font-bold mb-2' htmlFor="username">Username</label>
            <input 
                [(ngModel)]="form.username"
                #username="ngModel"
                required
                type="text"
                name="username"
                placeholder="username"
                class='rounded w-full py-2 px-3 text-gray-700 focus:outline-none focus:shadow-outline'
            />
        </div>
        <div>
            <label class="block text-gray-700 text-sm font-bold mb-2" htmlFor="password" >Password</label>
            <input 
                [(ngModel)]="form.password"
                #password="ngModel"
                required
                type="password"
                name="password"
                placeholder="password"
                class='class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"'
            />
        </div>
        <button class="bg-[#2a9fd6] hover:bg-[#0b73a0] text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
        Login
        </button>
        <span *ngIf="f.submitted && isLoginFailed">Login failed: {{errorMessage}}</span>
    </form>
</div>
