// Frontend/React/hudir/src/components/User.js
import { useRef, useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import axios from "axios";
import "./User.css";
import { BACKEND_URL } from "../constants";
import Image from "./Image";
import Posts from "./Posts";

function User(props){

    const { name } = useParams();
    const [userChange, setUserChange] = useState({user: null});
    const background = useRef(null);

    useEffect(() => {
        axios
            .get(
                BACKEND_URL.concat("/user/background/").concat(name),
                { responseType: 'arraybuffer'},
            )
            .then(response => {
                const base64 = btoa(
                    new Uint8Array(response.data).reduce(
                        (data, byte) => data + String.fromCharCode(byte),
                        '',
                    ),
                );
                background.current.style.backgroundImage = 'linear-gradient(0deg, rgba(0,0,0,0.7931373232886905) 0%, rgba(42,43,46,0.13767513841474088) 50%, rgba(121,9,9,0) 70%), url(data:;base64,' + base64 + '), linear-gradient(0deg, rgba(0,0,0,0.7931373232886905) 0%, rgba(42,43,46,0.13767513841474088) 39%, rgba(121,9,9,0) 55%)';
            });
        axios 
            .get(BACKEND_URL.concat("/user/getInfo/").concat(name))
            .then(response => {
                console.log(userChange);
                setUserChange({
                    ...userChange,
                    user: response.data
                });
            })
            .catch(err => {
                console.log(err);
            })
    }, [name]);

    function onChange(e){
        e.preventDefault();
        const formData = new FormData();

        formData.append('username', props.currentUser.username);
        formData.append('image', e.target.files[0]);

        axios
            .post(BACKEND_URL.concat('/user/setBackground'), formData)
            .then(response => {
                window.location.reload();
            })
            .catch(err => {
                console.log(err);
            })
    }

    function onChangePfp(e){
        e.preventDefault();
        const formData = new FormData();

        formData.append('username', props.currentUser.username);
        formData.append('image', e.target.files[0]);

        axios
            .post(BACKEND_URL.concat('/user/setPfp'), formData)
            .then(response => {
                window.location.reload();
            })
            .catch(err => {
                console.log(err);
            })
    }

    return(
        <div>
            <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossOrigin="anonymous"></link>
            <div ref={background} className="background">
                {
                    props.currentUser !== undefined && props.currentUser.username == name  ? (
                        <>
                            <form>
                                <input 
                                    type="file" 
                                    className="custom-file-input" 
                                    onChange={onChange} 
                                    name="fileToUpload" 
                                    id="fileToUpload" />
                                <label htmlFor="fileToUpload" className="background-change"><i className="fas fa-upload">
                                    </i>&nbsp;Change&nbsp;background&nbsp;(1920x640+)
                                </label>
                            </form>
                        </>
                    ) : (
                        <>  
                        
                        </>
                    )
                }
                <div className="md:container md:mx-auto justify-center profile_container">
                    {
                        props.currentUser !== undefined && props.currentUser.username == name ? (
                            <div className="flex justify-center">                        
                                <form>
                                    <input 
                                        type="file" 
                                        className="custom-file-input" 
                                        onChange={onChangePfp} 
                                        name="pfpUpload" 
                                        id="pfpUpload" 
                                    />
                                    <label htmlFor="pfpUpload" className="background-change"><i className="fas fa-upload">
                                        </i>&nbsp;Change&nbsp;profile picture&nbsp;
                                    </label>
                                </form>
                            </div>
                        ) : (
                            <></>
                        )   
                    }
                    <div className="flex justify-center mb-3">
                        <Image endpoint={"/user/pfp/".concat(name)} className="profile_picture"/>
                    </div>
                    <div className="flex justify-center">
                        <h2 className="username text-xl">{name}</h2>
                    </div>
                </div>
            </div>
            <div className="separator"></div>
            <Posts from="user" username={name} />
        </div>
    );
}

export default User;

// Frontend/Angular/hudir/src/app/user/user.component.ts
import { HttpClient } from '@angular/common/http';
import { Component, OnInit, ViewEncapsulation } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { TokenStorageService } from '../_services/token-storage.service';
import { BACKEND_URL } from '../constants';

class User {
  username: string = "";
  id: number = 0;
}

@Component({
  selector: 'app-user',
  templateUrl: './user.component.html',
  styleUrls: ['./user.component.css'],
  encapsulation: ViewEncapsulation.None
})
export class UserComponent implements OnInit {

  name: string = "";
  currentUser: User = new User();
  userChange: User = new User();
  isLoggedIn = false;

  constructor(private route: ActivatedRoute, private http: HttpClient, private tokenStorage: TokenStorageService) { }

  ngOnInit(): void {
    this.isLoggedIn = !!this.tokenStorage.getToken();
    if (this.isLoggedIn) {
      this.currentUser = this.tokenStorage.getUser();
    }
    this.name = this.route.snapshot.paramMap.get('name') || "";

    this.http
      .get(
        BACKEND_URL.concat("/user/background/").concat(this.name),
        { responseType: 'arraybuffer'},
      )
      .subscribe(response => {
        const base64 = btoa(
          new Uint8Array(response).reduce(
            (data, byte) => data + String.fromCharCode(byte),'',),
          );
          let background = document.getElementById('background');
          if(background !== null){
            background.style.backgroundImage = 'linear-gradient(0deg, rgba(0,0,0,0.7931373232886905) 0%, rgba(42,43,46,0.13767513841474088) 50%, rgba(121,9,9,0) 70%), url(data:;base64,' + base64 + '), linear-gradient(0deg, rgba(0,0,0,0.7931373232886905) 0%, rgba(42,43,46,0.13767513841474088) 39%, rgba(121,9,9,0) 55%)';
          }
      });

    this.http 
      .get<User>(BACKEND_URL.concat("/user/getInfo/").concat(this.name))
      .subscribe(response => {
          this.userChange = response;
      })
  }

  upload(e: Event){
    const formData = new FormData();
    const target = e.target as HTMLInputElement;

    if(target.files !== null){
      const file = target.files[0];
      formData.append('username', this.currentUser.username);
      formData.append('image', file);
    
      const endPoint = '/user/'.concat(target.id === "fileToUpload" ? "setBackground" : "setPfp");

      this.http
        .post(BACKEND_URL.concat(endPoint), formData)
        .subscribe({
          next: () => {
            window.location.reload();
          },
          error: (err) => {
            console.log(err);
          }
        });
    }    
  }

  checkUser(){
    return this.currentUser !== undefined && this.currentUser.username === this.name;
  }

}

<div>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossOrigin="anonymous" />
    <div id='background' class="background">
        <form *ngIf="checkUser()">
            <label class="background-change"><i class="fas fa-upload">
                </i>&nbsp;Change&nbsp;background&nbsp;(1920x640+)
                <input 
                    type="file" 
                    class="custom-file-input" 
                    name="fileToUpload" 
                    id="fileToUpload" 
                    (change)="upload($event)"
                />
            </label>
        </form>
        <div class="md:container md:mx-auto justify-center profile_container">
            <div *ngIf="checkUser()" class="flex justify-center">                        
                <form>
                    <label class="background-change"><i class="fas fa-upload">
                        </i>&nbsp;Change&nbsp;profile picture&nbsp;
                        <input 
                            type="file" 
                            class="custom-file-input" 
                            name="pfpUpload" 
                            id="pfpUpload" 
                            (change)="upload($event)"
                        />
                    </label>
                </form>
            </div>
            <div class="flex justify-center mb-3">
                <app-image [endpoint]="'/user/pfp/'.concat(name)" className="profile_picture"></app-image>
            </div>
            <div class="flex justify-center">
                <h2 class="username text-xl">{{name}}</h2>
            </div>
        </div>
    </div>
    <div class="separator"></div>
    <app-posts from="user" [username]="name"></app-posts>
</div>
